## YAML Template.
---
spring:
  application:
    name: auth-server

server:
   port: 9999

security:
   user:
      password: password   
   
eureka:
   instance:
      preferIpAddress: true
   client:
      serviceUrl:
         defaultZone: http://eureka-server:8761/eureka/        
         
management:
  security:
    enabled: false
    
logging:
   level: 
      org.springframework.security: INFO
    
    
