## YAML Template.
---
spring:
  application:
    name: zuul-proxy
    
server:
   port: 8080

logging:
   level:
      org.springframework.cloud.netflix.zuul.filters.ProxyRouteLocator: WARN

eureka:
   instance:
      preferIpAddress: true
   client:
      serviceUrl:
         defaultZone: http://eureka-server:8761/eureka/
