## YAML Template.
---
spring:
  application:
    name: user-service

security:
  oauth2:
    resource:
      userInfoUri: http://zuul-proxy:8080/auth-server/user  
      tokenInfoUri: http://zuul-proxy:8080/auth-server/oauth/check_token
    client:
      client-id: acme
      client-secret: acmesecret
      
server:
   port: 10080
   
eureka:
   instance:
      preferIpAddress: true
   client:
      serviceUrl:
         defaultZone: http://eureka-server:8761/eureka/        
         
management:
  security:
    enabled: false
    
logging:
   level: 
      org.springframework: INFO
    
    