## YAML Template.
---
spring:
  application:
    name: user-service
    
server:
   port: 10080
   
eureka:
   instance:
      preferIpAddress: true
   client:
      serviceUrl:
         defaultZone: http://eureka-server:8761/eureka/   
 